### ISSUE TITLE
[Tracker] Initial Release

### ISSUE THREAD

**Issue by holygits** [cennznet/cennzx-ui#12]
- [x] Liquidity Add/Remove
- [x] Exchange Buy/Sell
- [x] Handle decimal places dynamically
- [x] Support polkadot-js extension
